profiles/urls.py
from django.conf.urls import include
from django.urls import path
from . import views

app_name = "profiles"

urlpatterns = [
    path("<str:username>/",
         views.ProfileDetailView.as_view(), name="detail"),
    path("<str:username>/follow/",
         views.FollowView.as_view(), name="follow"),
]

til/urls.py
from django.contrib import admin
from django.conf.urls import include
from django.conf.urls.static import static
from django.conf import settings
from django.urls import path
from feed import urls as feed_urls
from profiles import urls as profiles_urls
from profiles import views as profile_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include(feed_urls, namespace="feed")),
    path('profile/',  profile_views.profile, name='profile'),
    path("profile/", include(profiles_urls, namespace="profiles")),
    path("", include("allauth.urls")),
]

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL,
        document_root=settings.MEDIA_ROOT
    )

profiles/models.py
from django.contrib.auth.models import User
from django.db import models
from django.db.models.signals import post_save
from django.dispatch import receiver
from sorl.thumbnail import ImageField


class Profile(models.Model):
    user = models.OneToOneField(
        User,
        on_delete=models.CASCADE,
        related_name="profile"
    )
    #image = ImageField(upload_to='profiles')
    image = ImageField(default='default.jpg', upload_to='profiles')
    image_bg = ImageField(
        default='default-bg.jpg', upload_to='profiles')

    def __str__(self):
        return f'{self.user.username} Profile'


@receiver(post_save, sender=User)
def create_user_profile(sender, instance, created, **kwargs):
    """Create a new Profile() object when a Django User is created"""
    if created:
        Profile.objects.create(user=instance)


@receiver(post_save, sender=User)
def save_profile(sender, instance, **kwargs):
    instance.profile.save()

profiles/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from .models import Profile


class UserUpdateForm(forms.ModelForm):
    email = forms.EmailField()

    class Meta:
        model = User
        fields = ['username',
                  'first_name', 'last_name', 'email']


class ProfileUpdateForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ['image', 'image_bg']
        labels = {
            'image': 'Avatar',
            'image_bg': 'Background img'
        }

profiles/views.py
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.decorators import login_required
from django.views.generic import DetailView, View
from django.http import JsonResponse
from django.shortcuts import render
from django.contrib import messages
from django.shortcuts import redirect

from feed.models import Post
from followers.models import Follower
from .forms import UserUpdateForm, ProfileUpdateForm


class ProfileDetailView(DetailView):
    http_method_names = ["get"]
    template_name = "profiles/detail.html"
    model = User
    context_object_name = "user"
    slug_field = "username"
    slug_url_kwarg = "username"

    def dispatch(self, request, *args, **kwargs):
        self.request = request
        return super().dispatch(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        user = self.get_object()
        context = super().get_context_data(**kwargs)
        context["total_posts"] = Post.objects.filter(author=user).count()
        context['you_follow_total'] = Follower.objects.filter(
            followed_by=user).count()
        if self.request.user.is_authenticated:
            context['you_follow'] = Follower.objects.filter(
                following=user, followed_by=self.request.user).exists()
        return context


class FollowView(LoginRequiredMixin, View):
    http_method_names = ["post"]

    def post(self, request, *args, **kwargs):
        data = request.POST.dict()
        if 'action' not in data or "username" not in data:
            return HttpResponseBadRequest("Missing data")

        try:
            other_user = User.objects.get(username=data['username'])
        except User.DoesNotExist:
            return HttpResponseBadRequest("Missing user")

        if data['action'] == 'follow':
            # follow
            follower, created = Follower.objects.get_or_create(
                followed_by=request.user,
                following=other_user
            )
        else:
            # unfollow
            try:
                follower = Follower.objects.get(
                    followed_by=request.user,
                    following=other_user
                )
            except Follower.DoesNotExist:
                follower = None

            if follower:
                follower.delete()

        return JsonResponse({
            'success': True,
            'wording': 'Unfollow' if data['action'] == 'follow' else 'Follow'
        })


# def register(request):
#    form = UserCreationForm()
#    return render(
#        request,
#        'profile/register.html',
#        {'form': form}
#    )

@login_required
def profile(request):
    if request.method == 'POST':
        u_form = UserUpdateForm(request.POST, instance=request.user)
        p_form = ProfileUpdateForm(
            request.POST, request.FILES, instance=request.user.profile)

        if u_form.is_valid() and p_form.is_valid():
            u_form.save()
            p_form.save()
            messages.success(request, f'Your account has been updated!')
            return redirect('profile')
    else:
        u_form = UserUpdateForm(instance=request.user)
        p_form = ProfileUpdateForm(instance=request.user.profile)

    context = {
        'u_form': u_form,
        'p_form': p_form
    }
    return render(request, 'profiles/profile.html', context)

profiles/templates/profiles/detail.html
{% extends 'base.html' %}
{% load thumbnail %}
{% block title %}{{ user.username }}{% endblock title %}

{% block body %}
<div class="text-center mb-4 ml-20 max-w-lg">
    <h3 class="font-light text-4xl text-green-700 w-full">
        Profile details
    </h3>
</div>
<!-- component from https://tailwindcomponents.com/component/profile-card -->
<div class="rounded rounded-t-lg overflow-hidden shadow-lg max-w-lg my-3 ml-20">
    {% thumbnail user.profile.image_bg "600x240" crop="center" as im %}
    <img src="{{ im.url }}" class="w-full" />
    {% endthumbnail %}
    <div class="flex justify-center -mt-8">
        {% thumbnail user.profile.image "150x150" crop="center" as im %}
        <img src="{{ im.url }}" class="rounded-full border-solid border-white border-2 -mt-3">
        {% endthumbnail %}
    </div>
    <div class="text-center px-3 pb-6 pt-2">
        <h3
            class="text-black text-lg font-bold w-11/12 mx-auto border-b border-green-300 rounded-md bg-gray-50 py-3 mb-4">
            <span class="font-normal">Username:</span>
            {{ user.username }}
        </h3>
        <p
            class="text-black text-lg font-bold w-11/12 mx-auto border-b border-green-300 rounded-md bg-gray-50 py-3 mb-4 capitalize">
            <span class="font-normal">First name:</span>
            {{ user.first_name }}
        </p>
        <p
            class="text-black text-lg font-bold w-11/12 mx-auto border-b border-green-300 rounded-md bg-gray-50 py-3 mb-4 capitalize">
            <span class="font-normal">Last name:</span>
            {{ user.last_name }}
        </p>
        <p
            class="text-black text-lg font-bold w-11/12 mx-auto border-b border-green-300 rounded-md bg-gray-50 py-3 mb-4">
            <span class="font-normal">Email:</span>
            {{ user.email }}
        </p>
        {% if request.user.is_authenticated %}
        {% if request.user != user %}
        <div class="mt-3">
            <button
                class="bg-white text-gray-800 font-bold rounded border-b-2 border-green-500 hover:border-green-600 hover:bg-green-500 hover:text-white shadow-md py-2 px-6 inline-flex items-center js-follow"
                data-username="{{ user.username }}" data-action="{% if you_follow %}un{% endif %}follow"
                data-url="{% url 'profiles:follow' user.username %}" type="button">
                <span class="mr-2 js-follow-text">
                    {% if you_follow %}
                    Unfollow
                    {% else %}
                    Follow
                    {% endif %}
                </span>
                <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24">
                    <path fill="currentcolor" d="M2.01 21L23 12 2.01 3 2 10l15 2-15 2z"></path>
                </svg>
            </button>
        </div>
        {% endif %}
        {% else %}
        <div class="mt-3 text-sm">Login to follow the user</div>
        {% endif %}
    </div>
    <div class="flex justify-center pb-3 text-grey-dark">
        <div class="text-center mr-3 border-r pr-3 border-green-300">
            <h2 class="text-base font-bold">{{ total_posts }}</h2>
            <span>Posts</span>
        </div>
        <div class="text-center">
            <h2 class="text-base font-bold">{{ you_follow_total }}</h2>
            <span>Friends</span>
        </div>
    </div>
</div>
{% endblock body %}

profiles/templates/profiles/profile.html
{% extends 'base.html' %}
{% load thumbnail %}
{% load crispy_forms_tags %}
{% block title %}{{ user.username }}{% endblock title %}

{% block body %}

<div class="text-center mb-4">
    <h3 class="font-light text-4xl text-green-700 w-full">
        Update profile for {{ user.username }}
    </h3>
</div>
<!-- component from https://tailwindcomponents.com/component/profile-card -->
<div class="rounded rounded-t-lg overflow-hidden shadow-lg">
    {% thumbnail user.profile.image_bg "600x240" crop="center" as im %}
    <img src="{{ im.url }}" class="w-full" />
    {% endthumbnail %}
    <div class="flex justify-center -mt-8">
        {% thumbnail user.profile.image "150x150" crop="center" as im %}
        <img src="{{ im.url }}" class="rounded-full border-solid border-white border-2 -mt-3">
        {% endthumbnail %}
    </div>

    <form method="POST" enctype="multipart/form-data" class="bg-white shadow-md rounded px-8 pt-6 pb-8">
        {% csrf_token %}

        {{ u_form|crispy }}

        <a href="{% url 'account_change_password' %}"
            class="change_password bg-green-500 hover:bg-green-700 text-white font-bold py-2 px-4 rounded focus:outline-none focus:shadow-outline inline-block mb-4"">Change password</a>

        {{ p_form|crispy }}

        <div class=" flex items-center justify-between">
            <button
                class="bg-green-500 hover:bg-green-700 text-white font-bold py-2 px-4 rounded focus:outline-none focus:shadow-outline"
                type="submit">
                Update
            </button>
</div>

</form>
</div>
{% endblock body %}

profiles/templates/profiles/register.html
{% extends "base.html" %}

{% block title %}Register new user{% endblock %}

{% block body %}
<div class="content-section">
    <form method="POST" class="bg-white shadow-md rounded px-8 pt-6 pb-8 mb-4">
        {% csrf_token %}
        <div class="mb-4">
            <h2 class="text-7xl text-green-700">Join now...</h2>
        </div>

        {{ form }}

        <div class="flex items-center justify-between">
            <button
                class="bg-green-500 hover:bg-green-700 text-white font-bold py-2 px-4 rounded focus:outline-none focus:shadow-outline"
                type="submit">
                Sign Up
            </button>
            <a class="inline-block align-baseline font-bold text-sm text-blue-500 hover:text-blue-800"
                href="{% url 'account_login' %}">
                Already have an account?
                <span class="text-sm text-green-700 font-semibold">
                    Sing in
                </span>
            </a>
        </div>

    </form>
</div>
{% endblock %}