feed/urls.py
from django.urls import path

from . import views

app_name = "feed"

urlpatterns = [
    path("", views.HomePage.as_view(), name='index'),
    path("selected-posts/", views.FriendsPostView.as_view(), name='friends_posts'),
    path("my-posts/", views.MyPostView.as_view(), name='my_posts'),
    path("<int:pk>/", views.PostDetailView.as_view(), name="detail"),
    path("new/", views.CreateNewPost.as_view(), name="new_post"),
]

til/urls.py
from django.contrib import admin
from django.conf.urls import include
from django.conf.urls.static import static
from django.conf import settings
from django.urls import path
from feed import urls as feed_urls
from profiles import urls as profiles_urls
from profiles import views as profile_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include(feed_urls, namespace="feed")),
    path('profile/',  profile_views.profile, name='profile'),
    path("profile/", include(profiles_urls, namespace="profiles")),
    path("", include("allauth.urls")),
]

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL,
        document_root=settings.MEDIA_ROOT
    )

til/templates/includes/post.html
{% load thumbnail %}

<!-- component is from https://tailwindcomponents.com/component/post-artical -->
<div class="max-w-4xl px-10 my-4 py-6 bg-white rounded-lg shadow-md ">
    <div class="items-center">
        <span class="font-light text-gray-600 block">{{ post.date|date:"F j, Y, g:i a" }}</span>
        <p class="mt-2 text-gray-600">
            {{ post.text }}
        </p>
    </div>
    <div class="flex justify-between items-center mt-4">
        {% if show_detail_link %}
        <a class="text-blue-600 hover:underline" href="{% url 'feed:detail' post.id %}">
            Read more
        </a>
        {% else %}
        <span>&nbsp;</span>
        {% endif %}
        <div>

            <a class="flex items-center" href="{% url 'profiles:detail' post.author.username %}">
                {% thumbnail post.author.profile.image "373x373" crop="center" as im %}
                <img class="mx-4 w-10 h-10 object-cover rounded-full hidden sm:block" src="{{ im.url }}" alt="avatar">
                {% endthumbnail %}
                <h1 class="text-gray-700 font-bold">{{ post.author.username }}</h1>
            </a>
        </div>
    </div>
</div>